dubbo:
  registry:
    address: zookeeper://localhost:2181  # ZooKeeper注册中心地址，如果是集群，使用逗号分隔
  application:
    name: webapi  # 应用名
  protocol:
    name: dubbo
    port: 20884  # 使用随机端口，也可以在0~65535之间指定端口
server.port: 8083